services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: fastapi
    ports:
      - '8000:8000'
    volumes:
      - './backend/app:/src/app'
      - './backend/dataset_archive:/src/dataset_archive'
      - './backend/main.py:/src/main.py'
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
      - FILE_DIRECTORY=/src/dataset_archive
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - monitoring_network
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.2
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - ./backend/mlruns:/mlflow/mlruns
    ports:
      - '5000:5000'
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns --host 0.0.0.0
    networks:
      - monitoring_network
  celery_worker:
    build:
      context: ./backend/app/tasks
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - './backend/dataset_archive:/app/dataset_archive'
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_ARCHIVE_PATH=/app/dataset_archive
      - VALID_ARCHIVE_MODULE_PATH=valid_archive
    command: celery -A main worker --loglevel=info
    networks:
      - monitoring_network
  redis:
    image: redis:7.4
    ports:
      - '6379:6379'
    networks:
      - monitoring_network

networks:
  monitoring_network:
