version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app 
      - ./backend/dataset_archive:/app/dataset_archive
    environment:
      - PYTHONUNBUFFERED=1
      - FILE_DIRECTORY=/app/dataset_archive
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
