FROM python:3.11-slim

WORKDIR /src

ARG ARCHIVE_PATH=/src/dataset_archive

COPY ./requirements.txt /src/requirements.txt

RUN pip install --no-cache-dir -r /src/requirements.txt

COPY ./app /src/app
COPY ./main.py /src/main.py

RUN mkdir -p $ARCHIVE_PATH && chmod 777 $ARCHIVE_PATH

# Celery 워커 실행
CMD ["celery", "-A", "app.tasks.main", "worker", "--loglevel=info"]